@baseUrl = http://localhost:8000

### GET all users
GET {{baseUrl}}/user

### POST create user
POST {{baseUrl}}/user/create
Content-Type: application/json

{
  "name": "alam",
  "email": "alam2@gmail.com",
  "password": "123123123"
}

### GET user by email
GET {{baseUrl}}/user/12345@gmail.com

### UPDATE user
PATCH {{baseUrl}}/books/670f0adc6fbb5020878c685c
Authorization: mykey
Content-Type: application/json

{
  "title": "sssssss",
  "authorId": "670b1e9b7386c36c8af76938"
}

### DELETE user
DELETE {{baseUrl}}/user/delete/6716f29b1fdbb1a4030cb25d

### Login User
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "alam@gmail.com",
  "password": "123123123"
}

### Protected Router
GET {{baseUrl}}/protected