@baseUrl = http://localhost:8000

### GET all users
GET {{baseUrl}}/api/v1/auth/users

### GET user by email
GET {{baseUrl}}/api/v1/auth/users/:email

### POST create user
POST {{baseUrl}}/api/v1/auth/users
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "12345678"
}

### DELETE user
DELETE {{baseUrl}}/api/v1/auth/users/:id

### Login User
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345678"
}

### Protected Router user
GET {{baseUrl}}/api/v1/auth/me