@baseUrl = http://localhost:8000

### GET all Hero
GET {{baseUrl}}/homepage

### POST create Hero
POST {{baseUrl}}/homepage/create-hero
Content-Type: application/json

{
  "title": "",
  "buttonUrl": ""
}

### GET Hero by ID
GET {{baseUrl}}/homepage/671e00dda6f4d80628ae87f2

### UPDATE Hero
PATCH {{baseUrl}}/homepage/update-hero/:id
Content-Type: application/json

{
  "title": "sssssss",
  "buttonUrl": "670b1e9b7386c36c8af76938"
}

### DELETE Hero
DELETE {{baseUrl}}/homepage/delete-hero/6720939dbe1dbc3e3e7fef22